export default [
    {
        name:"America",
        img:"img/nations/American.png",
        id:1
    },
    {
        name:"Arabian",
        img:"img/nations/Arabian.png",
        id:2
    },
    {
        name:"Austria",
        img:"img/nations/Austrian.png",
        id:3
    },
    {
        name:"Aztec",
        img:"img/nations/Aztec.png",
        id:4
    },
    {
        name:"Babylon",
        img:"img/nations/Babylonian.png",
        id:5
    },
    {
        name:"Brazil",
        img:"img/nations/Brazilian.png",
        id:6
    },
    {
        name:"Byzantine",
        img:"img/nations/Byzantine.png",
        id:7
    },
    {
        name:"Carthage",
        img:"img/nations/Carthaginian.png",
        id:8
    },
    {
        name:"Celtic",
        img:"img/nations/Celtic.png",
        id:9
    },
    {
        name:"China",
        img:"img/nations/Chinese.png",
        id:10
    },
    {
        name:"Denmark",
        img:"img/nations/Danish.png",
        id:11
    },
    {
        name:"Dutch",
        img:"img/nations/Dutch.png",
        id:12
    },
    {
        name:"Egypt",
        img:"img/nations/Egyptian.png",
        id:13
    },
    {
        name:"England",
        img:"img/nations/English.png",
        id:14
    },
    {
        name:"Ethiopia",
        img:"img/nations/Ethiopian.png",
        id:15
    },
    {
        name:"France",
        img:"img/nations/French.png",
        id:16
    },
    {
        name:"Germany",
        img:"img/nations/German.png",
        id:17
    },
    {
        name:"Greece",
        img:"img/nations/Greek.png",
        id:18
    },
    {
        name:"Huns",
        img:"img/nations/Hunnic.png",
        id:19
    },
    {
        name:"Incs",
        img:"img/nations/Incan.png",
        id:20
    },
    {
        name:"India",
        img:"img/nations/Indian.png",
        id:21
    },
    {
        name:"Indonesia",
        img:"img/nations/Indonesian.png",
        id:22
    },
    {
        name:"Iroquois",
        img:"img/nations/Iroquois.png",
        id:23
    },
    {
        name:"Japan",
        img:"img/nations/Japanese.png",
        id:24
    },
    {
        name:"Korea",
        img:"img/nations/Korean.png",
        id:25
    },
    {
        name:"Maya",
        img:"img/nations/Mayan.png",
        id:26
    },
    {
        name:"Mongolia",
        img:"img/nations/Mongolian.png",
        id:27
    },
    {
        name:"Morocco",
        img:"img/nations/Moroccan.png",
        id:28
    },
    {
        name:"Ottoman",
        img:"img/nations/Ottoman.png",
        id:29
    },
    {
        name:"Persia",
        img:"img/nations/Persian.png",
        id:30
    },
    {
        name:"Poland",
        img:"img/nations/Polish.png",
        id:31
    },
    {
        name:"Polynesia",
        img:"img/nations/Polynesian.png",
        id:32
    },
    {
        name:"Portugal",
        img:"img/nations/Portuguese.png",
        id:33
    },
    {
        name:"Rome",
        img:"img/nations/Roman.png",
        id:34
    },
    {
        name:"Russia",
        img:"img/nations/Russian.png",
        id:35
    },
    {
        name:"Shoshone",
        img:"img/nations/Shoshone.png",
        id:36
    },
    {
        name:"Siam",
        img:"img/nations/Siamese.png",
        id:37
    },
    {
        name:"Songhai",
        img:"img/nations/Songhai.png",
        id:38
    },
    {
        name:"Spain",
        img:"img/nations/Spanish.png",
        id:39
    },
    {
        name:"Sweden",
        img:"img/nations/Swedish.png",
        id:40
    },
    {
        name:"Venice",
        img:"img/nations/Venetian.png",
        id:41
    },
    {
        name:"Zulu",
        img:"img/nations/Zulu.png",
        id:42
    }
]

